// <auto-generated />
namespace HLWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1212));
        
        string IMigrationMetadata.Id
        {
            get { return "202112120512059_1212"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
