// <auto-generated />
namespace HLWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
<<<<<<< HEAD:HLWEB/Migrations/202112120512059_1212.Designer.cs
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1212));
        
        string IMigrationMetadata.Id
        {
            get { return "202112120512059_1212"; }
=======
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202112110648475_InitialModel"; }
>>>>>>> 8251886ef6110a1423cc81043d787dd0172b00b7:HLWEB/Migrations/202112110648475_InitialModel.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
